import type { AsciiFrame } from '@/lib/ascii-engine'
import type { ColorMode, ExportLoop } from '@/lib/constants'

export interface ANSIExportOptions {
  frames: AsciiFrame[]
  fps: number
  loop: ExportLoop
  colorMode: ColorMode
  fgColor: string // hex
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  return [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
  ]
}

function escapeForPrintf(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/%/g, '%%')
    .replace(/'/g, "'\"'\"'")
}

function buildMonochromeLine(line: string): string {
  return escapeForPrintf(line)
}

function buildColoredLine(cells: { char: string; r: number; g: number; b: number }[]): string {
  let result = ''
  let prevR = -1, prevG = -1, prevB = -1

  for (const cell of cells) {
    const r = cell.r | 0
    const g = cell.g | 0
    const b = cell.b | 0
    if (r !== prevR || g !== prevG || b !== prevB) {
      result += `\\033[38;2;${r};${g};${b}m`
      prevR = r
      prevG = g
      prevB = b
    }
    result += escapeForPrintf(cell.char)
  }

  return result
}

export function generateExportANSI(options: ANSIExportOptions): string {
  const { frames, fps, loop, colorMode, fgColor } = options
  const delay = (1 / fps).toFixed(4)
  const [fgR, fgG, fgB] = hexToRgb(fgColor)

  const lines: string[] = []

  // Header
  lines.push('#!/bin/bash')
  lines.push('# ASCII Animation generated by ASCIIfy')
  lines.push(`# Frames: ${frames.length}, FPS: ${fps}`)
  lines.push('')
  lines.push("trap 'printf \"\\033[0m\"; tput cnorm; exit' INT TERM")
  lines.push('tput civis')
  lines.push(`DELAY=${delay}`)
  lines.push('')

  // Set monochrome color once if not colored mode
  if (colorMode !== 'colored') {
    lines.push(`printf '\\033[38;2;${fgR};${fgG};${fgB}m'`)
  }

  // Build frame rendering function
  lines.push('render_frames() {')

  for (let i = 0; i < frames.length; i++) {
    const frame = frames[i]
    const frameLines = frame.text.split('\n')

    lines.push("  printf '\\033[H'")

    if (colorMode === 'colored') {
      for (const row of frame.cells) {
        lines.push(`  printf '${buildColoredLine(row)}\\n'`)
      }
    } else {
      for (const line of frameLines) {
        lines.push(`  printf '${buildMonochromeLine(line)}\\n'`)
      }
    }

    lines.push('  sleep $DELAY')
    lines.push('')
  }

  lines.push('}')
  lines.push('')

  // Loop wrapper
  if (loop === 'forever') {
    lines.push('while true; do')
    lines.push('  render_frames')
    lines.push('done')
  } else if (loop === 'once') {
    lines.push('render_frames')
  } else {
    lines.push(`for i in $(seq 1 ${loop}); do`)
    lines.push('  render_frames')
    lines.push('done')
  }

  lines.push('')
  lines.push("printf '\\033[0m'")
  lines.push('tput cnorm')

  return lines.join('\n')
}
